#!/usr/bin/env bash

# Uncomment for debugging
# echo "prerm invoked: $0 $@"

if [[ $1 == "remove"]]
then
    /usr/bin/pyhole-purge
    rm -rf "/usr/lib/python3.4/pyhole/__pycache__/"
elif [[ $1 == "upgrade"]]
    # Do nothing
    :
fi

